#ifndef _MODBUS_COMMON_H
#define _MODBUS_COMMON_H

//define modbus function code 
#define MB_FUNCCODE_READHOLDINGREG				0x3U
#define MB_FUNCCODE_WIRTEHOLDINGREG				0x6U
#define MB_FUNCCODE_WIRTEHOLDINGREG_MUL			0x10U




//define data reg length
#define MASTER_DATAREG_MAX_LEN					0x50U
#define MASTER_SENDREG_MAX_LEN					80U

//define data reg length
#define SLAVE_DATAREG_START_ADDR				0x00U
#define SLAVE_DATAREG_MAX_LEN					0x50U
#define SLAVE_SENDREG_MAX_LEN					80U


//define slave adress
#define MB_SLAVE_ADRESS							0x01U

//define err mask
#define MB_ERR_MASK								0x80U

#define READ_HOLDREG_ERR						0x83U
#define WIRTE_SIGNALE_ERR						0x86U
#define WIRTE_MULTREG_ERR						0x90U


typedef enum __MBERRCODE
{
	//define modbus error code
	MB_ERR_NONE=0x00U,
		
	MB_ERR_ILLEGAL_FUNCCODE=0x01U,
	MB_ERR_ILLEGAL_DATAADDR=0x02U,
	MB_ERR_ILLEGAL_DATAVALUE=0x03U,
	MB_ERR_SLAVE_MACH_FAULT=0x04U,
	MB_ERR_DELAY_PROCESS=0x05U,
	MB_ERR_SALVE_BUSY=0x06U,
	MB_ERR_SAVE_PARITY_ERR=0x08U,
	MB_ERR_UNAPPLICABLE_GATEWAY=0x0AU,
	MB_ERR_GATEWAY_DEVICE_RESPONS_FAIL=0x0BU,
		
	//define extend err code
	MB_EXTEND_ERR_FORBID_OPER=0x40U,
	MB_EXTEND_ERR_HAVENOT_LEARN_PHASE=0x60U,
	MB_EXTEND_ERR_UNDEFINE_ERR=0xFFU,
		
	//define local err code
	MB_LOCAL_ERR_SLAVE_ADDR_ERR=0xE0U,
	MB_LOCAL_ERR_INVALID_BUF_DATA=0xE1U,
	MB_LOCAL_ERR_RESPONSES_TIMEOUT=0xE2U,
	MB_LOCAL_ERR_ILLEGAL_FUNCTION_ADDR=0xE3U,
	MB_LOCAL_ERR_ILLEGAL_DATAREG_ADDR=0xE4U,
	MB_LOCAL_ERR_SEND_BUFFER_IS_FULL=0xE5U,
	MB_LOCAL_ERR_TRANSIT_FAIL=0xE6U,
	MB_LOCAL_ERR_RETURNDATA_ERR=0xE7U,
}MBERRCODE;

typedef enum __MODEBUSMODE
{
	MB_MODE_NOMAL=0,
	MB_MODE_TRANSIT
}MODEBUSMODE;


#endif
