// Generated by gencpp from file learn_communication/AddTwoInts.msg
// DO NOT EDIT!


#ifndef LEARN_COMMUNICATION_MESSAGE_ADDTWOINTS_H
#define LEARN_COMMUNICATION_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <learn_communication/AddTwoIntsRequest.h>
#include <learn_communication/AddTwoIntsResponse.h>


namespace learn_communication
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace learn_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learn_communication::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::learn_communication::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::learn_communication::AddTwoInts > {
  static const char* value()
  {
    return "learn_communication/AddTwoInts";
  }

  static const char* value(const ::learn_communication::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::learn_communication::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::learn_communication::AddTwoInts >
template<>
struct MD5Sum< ::learn_communication::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learn_communication::AddTwoInts >::value();
  }
  static const char* value(const ::learn_communication::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learn_communication::AddTwoIntsRequest> should match
// service_traits::DataType< ::learn_communication::AddTwoInts >
template<>
struct DataType< ::learn_communication::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::learn_communication::AddTwoInts >::value();
  }
  static const char* value(const ::learn_communication::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learn_communication::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::learn_communication::AddTwoInts >
template<>
struct MD5Sum< ::learn_communication::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learn_communication::AddTwoInts >::value();
  }
  static const char* value(const ::learn_communication::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learn_communication::AddTwoIntsResponse> should match
// service_traits::DataType< ::learn_communication::AddTwoInts >
template<>
struct DataType< ::learn_communication::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::learn_communication::AddTwoInts >::value();
  }
  static const char* value(const ::learn_communication::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARN_COMMUNICATION_MESSAGE_ADDTWOINTS_H
